### ISSUE TITLE
[Algorithm] - Quick Sort

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#1]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Quick Sort

- **Language:** Python

**Comment by Chaitanya-Raj** [comment]
I would like to add this one to the repo

**Comment by iam-abbas** [comment]
Go ahead @Chaitanya-Raj
