### ISSUE TITLE
[Algorithm] - Insertion Sort

### ISSUE THREAD

**Issue by rohanmarwaha222** [iam-abbas/cs-algorithms#106]
# CS - Algorithm
-  This algorithm is not available in the repository currently.

##  Information

- **Insertion Sort:**

- **C++:**

**Comment by Avijeetpandey25** [comment]
I have added the insertion sort

**Comment by iam-abbas** [comment]
Go ahead

**Comment by Avijeetpandey25** [comment]
thank you

**Comment by ayaankhan98** [comment]
i wish to work on this algorithm in C++

**Comment by divakar-lakhera** [comment]
can i work on this algorithm in c++?

**Comment by Tawishi** [comment]
I can work on this algorithm. Can I be assigned this?

**Comment by divakar-lakhera** [comment]
Insertion Sort in C++ #155

**Comment by divakar-lakhera** [comment]
Added Insertion Sort in C++ #155

**Comment by divakar-lakhera** [comment]
#155

**Comment by divakar-lakhera** [comment]
Added Insertion Sort in C++ #155
