### ISSUE TITLE
[Algorithm] - Knapsack-DP

### ISSUE THREAD

**Issue by torres07** [iam-abbas/cs-algorithms#114]
# CS - Algorithm
- [ ]  This algorithm is not available in the repository currently.
- [x] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Knapsack - Dynamic Programming**

- **Language: C++**

**Comment by Kuljeet-123** [comment]
@torres07  I would like to work on this ,can you please assign this to me.
