### ISSUE TITLE
[Algorithm] - Sieve of Eratosthenes (Math/C++)

### ISSUE THREAD

**Issue by mujtaba1747** [iam-abbas/cs-algorithms#118]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Sieve of Eratosthenes

- **Language:** C++

**Comment by Apoorv-Gaurav-Agarwal** [comment]
is this available?

**Comment by divakar-lakhera** [comment]
Added Sieve of Eratosthenes in C++ #148

**Comment by mujtaba1747** [comment]
@divakar-lakhera 
With all due respect :
I have already added Sieve of Eratosthenes, please remove your pull request.
It's not implemented in Python and other languages, do that instead or else there is a chance that both our pull requests get marked as SPAM.
