### ISSUE TITLE
[Algorithm] - Insertion Sort

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#12]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Insertion Sort

- **Language:** Any

**Comment by AminuBishir** [comment]
Is this issue still open?

**Comment by pinathon** [comment]
I want to implement same in C++. Can you assign this to me?
