### ISSUE TITLE
[Algorithm] - Closest Pair of Points

### ISSUE THREAD

**Issue by LluisCS** [iam-abbas/cs-algorithms#127]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Closest Pair of Points

- **Language:** C++

**Comment by raffleberry** [comment]
Can I work on this?

**Comment by LluisCS** [comment]
Well, I posted this issue do work on it myself. It's according to the guidelines.
