### ISSUE TITLE
[Algorithm] - BFS

### ISSUE THREAD

**Issue by pruthvigh** [iam-abbas/cs-algorithms#133]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** BFS

- **Language:** Python

**Comment by Nikronic** [comment]
I would like to handle this issue. Thank you.

**Comment by pruthvigh** [comment]
Created a new pull request for this issue. Thanks.
