### ISSUE TITLE
[Algorithm] - FCFS

### ISSUE THREAD

**Issue by sweezy793** [iam-abbas/cs-algorithms#138]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
First Come, First Serve(FCFS) CPU Scheduling algorithm
- **Language:**
Python

**Comment by sweezy793** [comment]
@iam-abbas Please assign this to me :)

**Comment by iam-abbas** [comment]
Go ahead

**Comment by himanshututeja1998** [comment]
Want this in c++

**Comment by APushpendra08** [comment]
Can I have this issue assigned, if it's possible?

**Comment by iam-abbas** [comment]
Go ahead if you’re doing it in different languages
