### ISSUE TITLE
[Algorithm] - CountingSort

### ISSUE THREAD

**Issue by AkhzarFarhan** [iam-abbas/cs-algorithms#140]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Counting Sort

- **Language:** CPP

**Comment by iam-abbas** [comment]
Go ahead

**Comment by s1042992** [comment]
just made a pr
