### ISSUE TITLE
[Algorithm] - Maximum size sub-square with all 0s in a given 2D matrix

### ISSUE THREAD

**Issue by atjustbeinghumaid** [iam-abbas/cs-algorithms#149]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
Maximum size sub-square with all 0s in a given 2D matrix
- **Language:**
C++

**Comment by atjustbeinghumaid** [comment]
Working on it

**Comment by iam-abbas** [comment]
Awesome go ahead

**Comment by 19shubh99** [comment]
i am contributing to it
