### ISSUE TITLE
[Algorithm] - Modular Exponentiation(Math/C++)

### ISSUE THREAD

**Issue by raffleberry** [iam-abbas/cs-algorithms#156]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Modular Exponentiation

- **Language:** C++

**Comment by kushalforcode** [comment]
i wanna contribute to it

**Comment by raffleberry** [comment]
I have already completed it
