### ISSUE TITLE
[Algorithm] - m Coloring Problem

### ISSUE THREAD

**Issue by sweezy793** [iam-abbas/cs-algorithms#174]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
m Coloring Problem using Backtracking
- **Language:**
Python

**Comment by sweezy793** [comment]
I would like to work on this

**Comment by iam-abbas** [comment]
Go ahead
