### ISSUE TITLE
[Algorithm] - Wine Problem(Dynamic programming)

### ISSUE THREAD

**Issue by agrawalsajal02** [iam-abbas/cs-algorithms#190]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Wine Problem
- ** Algorithm Description:** Given n wines in a row, with integers denoting the cost of each wine respectively. Each year you can sale the first or the last wine in the row. However, the price of wines increases over time. Let the initial profits from the wines be c1, c2, c3…cn. On the Yth year, the profit from the ith wine will be Y*ci. For each year, your task is to print “beg” or “end” denoting whether first or last wine should be sold. Also, calculate the maximum profit from all the wines.
- **Language:** c++

**Comment by agrawalsajal02** [comment]
working on it

**Comment by MananJethwani** [comment]
i solved the problem can i submit it??
