### ISSUE TITLE
[Algorithm] - rat in a maze

### ISSUE THREAD

**Issue by agrawalsajal02** [iam-abbas/cs-algorithms#195]
# CS - Algorithm rat in a maze problem
- [x]  This algorithm is not available in the repository currently.
- [ ]  If it is, My Algorithm is implemented in a different method.

##  Information

-  **Algorithm Name:** rat in a maze (Backtracking)

-  **Language:** cpp

**Comment by Shubham230198** [comment]
Hi, i like work on this problem, but it seems like you have already  uploaded the solution, so what you want me to do ?

**Comment by agrawalsajal02** [comment]
i have uploaded in cpp.
you can upoad it in java or python
