### ISSUE TITLE
[Algorithm] - Bubble Sort

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#2]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Bubble Sort

- **Language:** Python

**Comment by Thesmader** [comment]
I would like to add this algorithm to the repository.

**Comment by Deepansharora27** [comment]
@iam-abbas I would like to Implement the Same in C++ ? Assign it to me
