### ISSUE TITLE
Add Algorithms to this Repository

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#20]
Hey guys,

Hope you guys are having a great time with Hacktoberfest. This repo consists of Algorithms in Python/C/Cpp but it’s currently not done yet. There are many algos that need to be added.

- Read the ReadME file
- Make an Issue of the algorithm you want to add
- submit PR

 And I will merge your request

**Comment by mahalrupi** [comment]
Added a prims algorithm as a pull request
#24

**Comment by sawlani1234** [comment]
Can we still contribute algorithms to this repository as part of HacktoberFest?
