### ISSUE TITLE
[Algorithm] - Bucket Sort

### ISSUE THREAD

**Issue by muskan077** [iam-abbas/cs-algorithms#216]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
Bucket Sort
- **Language:**
C++

**Comment by Golomann** [comment]
Created BucketSort.cpp #363

**Comment by Golomann** [comment]
Made.
