### ISSUE TITLE
[Algorithm] - ceaser cipher

### ISSUE THREAD

**Issue by nitishsai9** [iam-abbas/cs-algorithms#231]
# CS - Caesar Cipher
- [ ✔️]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
Caesar Cipher
- **Language:**
Python,c++

**Comment by rock8forever** [comment]
Can i take this?

**Comment by rock8forever** [comment]
https://github.com/iam-abbas/cs-algorithms/pull/300
ok, thats done
