### ISSUE TITLE
[Algorithm] - DFS RECURSIVE

### ISSUE THREAD

**Issue by nitishsai9** [iam-abbas/cs-algorithms#233]
# CS - Algorithm
- [ ]  This algorithm is not available in the repository currently.
- [✔️ ] If it is, My Algorithm is implemented in a different method.

##  Information
 Depth First Search Algorithm - C recursive Implementation using Arrays
- **Algorithm Name:**
Depth First Search Algorithm
- **Language:**
C

**Comment by rajneeshkumar146** [comment]
i want to grab it. please assign to me

**Comment by adavijit** [comment]
can I please contribute to this?
