### ISSUE TITLE
[Algorithm] - Static Hashing

### ISSUE THREAD

**Issue by nitishsai9** [iam-abbas/cs-algorithms#234]
# CS -Static Hashing
- [ ✔️]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  InformationStatic Hashing is another form of the hashing problem which allows users to perform lookups on a finalized dictionary set .
- **Algorithm Name:**
Static Hashing
- **Language:**
cpp

**Comment by rock8forever** [comment]
Can i take this?
