### ISSUE TITLE
[Algorithm] - TOWER OF HANOI

### ISSUE THREAD

**Issue by Sahastracookcoder1** [iam-abbas/cs-algorithms#235]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [x] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Tower of hanoi

- **Language:** c++, python,java

**Comment by Sahastracookcoder1** [comment]
please assign me @iam-abbas

**Comment by iam-abbas** [comment]
Go ahead

**Comment by divakar-lakhera** [comment]
can i do this in C++?
