### ISSUE TITLE
Fibonacci Search

### ISSUE THREAD

**Issue by ShubhankarKG** [iam-abbas/cs-algorithms#273]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Fibonacci Search**

- **Language: C**

**Comment by ShubhankarKG** [comment]
Please assign it to me

**Comment by MichelleCordeiro** [comment]
Please assign me @iam-abbas
