### ISSUE TITLE
[Algorithm] - Floyd Warsall For all pair shortest path

### ISSUE THREAD

**Issue by asifsadek** [iam-abbas/cs-algorithms#282]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.

- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:*Floyd Warsall For all pair shortest path*

- **Language:*C++*

**Comment by Shiv1202** [comment]
Can I submit this algorithm in JavaScript?

**Comment by asifsadek** [comment]
> Can I submit this algorithm in JavaScript?

I think you can .

**Comment by Shiv1202** [comment]
Okk thanks!!
