### ISSUE TITLE
[Algorithm] - Doubly Linked List

### ISSUE THREAD

**Issue by amritansh22** [iam-abbas/cs-algorithms#288]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Doubly Linked List**

- **Language: C++**

**Comment by Sahastracookcoder1** [comment]
i am interested to do

**Comment by sark-2110** [comment]
please this task to me as I have practising linked list from time.
