### ISSUE TITLE
 Reverse Polish notation, RPN

### ISSUE THREAD

**Issue by PkiId** [iam-abbas/cs-algorithms#297]
# CS - Algorithm
 This algorithm is not available in the repository currently.

##  Information

- **Algorithm Name:**
 Reverse Polish notation, RPN
- **Language:**
C++

**Comment by soniakash1998** [comment]
I would like to work on this issue. Could you please tell me what all programs that I should add to this repository?

**Comment by PkiId** [comment]
Sorry, but I have already added it, it's Calculator folder in this project. It's getting a regular mathematical expression, for example 2+(3*cos(90)), convert it to the PRN and count it

**Comment by soniakash1998** [comment]
something else that I can do in other repositories?
