### ISSUE TITLE
[Algorithm] - Binary Search

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#3]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Binary Search

- **Language:** Python

**Comment by Deepansharora27** [comment]
Can I Code for the Same in C++ if you dont mind ?

**Comment by iam-abbas** [comment]
@deepansharora27 yes you can but rise an issue regarding the same. Please check the Readme

**Comment by Deepansharora27** [comment]
Okay Thanks Assign it to me I'll Do it

**Comment by Deepansharora27** [comment]
@iam-abbas How should I make the Pull request in the Order in which you have said .i.e. AlgorithmType/AlgorithmName/Language

**Comment by iam-abbas** [comment]
Yes

**Comment by Deepansharora27** [comment]
@iam-abbas I am asking how should i make it in that order Can u guide me

**Comment by Deepansharora27** [comment]
Or Will it work if i simply make a PullRequest without that Folder ?

**Comment by Deepansharora27** [comment]
@iam-abbas I have made a Pull Request Can u please check ?

**Comment by iam-abbas** [comment]
yes your request is merged
