### ISSUE TITLE
[Algorithm] - Comb_Sort

### ISSUE THREAD

**Issue by muskan077** [iam-abbas/cs-algorithms#359]
# CS - Algorithm
- [ ] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**
     Comb-Sort
- **Language:**
     C++

**Comment by Golomann** [comment]
CombSort.cpp  #362

**Comment by Golomann** [comment]
Made..
