### ISSUE TITLE
[Algorithm] - An Optimal Stopping Problem 

### ISSUE THREAD

**Issue by abrar-syed** [iam-abbas/cs-algorithms#366]
# CS - Algorithm
- [ ] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Optimal Stopping Algorithm

- **Language:C++

**Comment by Apoorv-Gaurav-Agarwal** [comment]
I would like to work on this

**Comment by Apoorv-Gaurav-Agarwal** [comment]
Also, Can I implement any problem that uses this algorithm in the solution or any specific?

**Comment by Apoorv-Gaurav-Agarwal** [comment]
#371
