### ISSUE TITLE
[Algorithm] - Egg Dropping

### ISSUE THREAD

**Issue by niteshbharti005101** [iam-abbas/cs-algorithms#396]
# CS - Algorithm
- [ ] I have starred this repository
- [ ] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Egg Dropping

- **Language: C++

**Comment by rudradesai200** [comment]
Already solved . Path :- /C++/egg_dropping.cpp
