### ISSUE TITLE
[Algorithm] - Longest Common Subsequence

### ISSUE THREAD

**Issue by niteshbharti005101** [iam-abbas/cs-algorithms#398]
# CS - Algorithm
- [ ] I have starred this repository
- [ ] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name: Longest Common Subsequence

- **Language: C++

**Comment by Nishant110699** [comment]
i like to work on it.
