### ISSUE TITLE
[Algorithm] - Parenthesis Balancing

### ISSUE THREAD

**Issue by prajwal-naik** [iam-abbas/cs-algorithms#473]
# CS - Algorithm
- [ ] I have starred this repository
- [ ] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- Parenthesis Matching

- Python

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by prajwal-naik** [comment]
I have finished addressing this issue. Making an issue was a part of the process to request a pull.
