### ISSUE TITLE
[Algorithm] - Tree Traversal Using C

### ISSUE THREAD

**Issue by prajwal-naik** [iam-abbas/cs-algorithms#475]
# CS - Algorithm
- [ ] I have starred this repository
- [ ] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- Tree Traversal

- C

**Comment by kushalforcode** [comment]
I wish to work on this project

**Comment by bhavanshu-1112** [comment]
i wish to work on this project
