### ISSUE TITLE
[Algorithm] - Tree Views and Diagonal Tree Traversal

### ISSUE THREAD

**Issue by ankank30** [iam-abbas/cs-algorithms#483]
# CS - Algorithm
- [ ] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Left, top and bottom view of the tree and Diagonal tree traversal.

- **Language:** C++

**Comment by sawlani1234** [comment]
Kindly assign me this issue.I will add programs for left,top and bottom views in a tree.

**Comment by sainikhit2k** [comment]
Is it okay if create a PR ?

**Comment by sainikhit2k** [comment]
can you assign me this one ?
i can do this
