### ISSUE TITLE
[Algorithm] - Quick Sort C++ 

### ISSUE THREAD

**Issue by HoaNP** [iam-abbas/cs-algorithms#490]
# CS - Algorithm
- [x] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [x] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Quick Sort

- **Language:** C++

**Comment by Rajratnpranesh** [comment]
@HoaNP I want to contribute to the repo. Kindly assign me the issue, I will add the QuickSort algorithm in C++.
