### ISSUE TITLE
[BubbleSort] in C

### ISSUE THREAD

**Issue by Rajratnpranesh** [iam-abbas/cs-algorithms#495]
# CS - Algorithm
- [x] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **BubbleSort**

- **C**

**Comment by Abhishek-Mittall** [comment]
i will take this issue .Please Assign me this.

**Comment by parthvyas7** [comment]
I will take this issue .Please Assign me this.
