### ISSUE TITLE
Binary-Search 

### ISSUE THREAD

**Issue by Deepansharora27** [iam-abbas/cs-algorithms#5]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.

##  Information

- Binary Search 

- C++

**Comment by kgautam01** [comment]
If the implementation in Python is still required, Kindly assign it to me.
Thanks.

**Comment by iam-abbas** [comment]
@kgautam01 go ahead

**Comment by Sushant2** [comment]
hey,can i write it in c,,,,if possible assign it to me or i have to create a new pull request...

**Comment by kgautam01** [comment]
Created a PR for binary search implementation in Python. Kindly have a look.
