### ISSUE TITLE
Sieve of Eratosthenes, Segmented Sieve

### ISSUE THREAD

**Issue by srinath1999** [iam-abbas/cs-algorithms#55]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Sieve of Eratosthenes, Segmented Sieve

- **Language:** C++

**Comment by ricky1812** [comment]
i would like to solve this issue
