### ISSUE TITLE
[Algorithm] -CATALAN NUMBER

### ISSUE THREAD

**Issue by zahirahmed88** [iam-abbas/cs-algorithms#606]
# CS - Algorithm
- [x] This algorithm is not available in the repository currently.
- [x] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:*CATALAN NUMBER*

- **Language:*C++,SCALA,RUBY*

**Comment by xenowits** [comment]
can i be assigned to this?
