### ISSUE TITLE
Euler Totient Function

### ISSUE THREAD

**Issue by xenowits** [iam-abbas/cs-algorithms#611]
# CS - Algorithm
- [x] I have starred this repository
- [ ] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

Implementation of Euler totient function in one of the following languages required.
The euler function is an important concept in Number theory and has many applications in gcd related problems.

- Euler Totient Function

- C++/Go/Python

**Comment by shubhgup11** [comment]
assign it to me
