### ISSUE TITLE
Shortest Job First CPU scheduling algorithm 

### ISSUE THREAD

**Issue by PrakharKopergaonkar** [iam-abbas/cs-algorithms#62]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:**  Shortest Job First CPU Scheduling Algorithm (with arrival time zero for all processes).  

- **Language:** C

**Comment by tanaytoshniwal** [comment]
I would like to work on this issue @PrakharKopergaonkar

**Comment by iam-abbas** [comment]
@tanaytoshniwal please read README.md

**Comment by tanaytoshniwal** [comment]
#64 I've implemented the algorithm in C++ language in the following directory:
Operating Systems/Shortest Job First CPU Scheduling Algorithm/CPP/shortestjobfirst.cpp
