### ISSUE TITLE
[Algorithm] - N Queen

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#63]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** N Queen

- **Language:** Cpp, C

**Comment by tanaytoshniwal** [comment]
I would like to implement this algorithm in C++ @iam-abbas

**Comment by tanaytoshniwal** [comment]
I have submitted a pull request implementing this in C++ #64
