### ISSUE TITLE
[Quick Sort] 

### ISSUE THREAD

**Issue by sakshamsachdeva** [iam-abbas/cs-algorithms#659]
# CS - Algorithm
- [x] I have starred this repository
- [x] This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Quick Sort:**

- **Kotlin:**

**Comment by rudradesai200** [comment]
Does it need to be in kotlin only? or will it be okay to be in python

**Comment by abhaymaniyar** [comment]
Done it in Java Language.
