### ISSUE TITLE
[Algorithm] - Knight’s Tour

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/cs-algorithms#66]
# CS - Algorithm
- [x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

- **Algorithm Name:** Knight’s Tour

- **Language:** Cpp, C, Python

**Comment by ajaykumar1018** [comment]
I can implement this in c @iam-abbas

**Comment by makajeez** [comment]
in Python coming in

**Comment by makajeez** [comment]
KnightTour.py #251
