### ISSUE TITLE
[Algorithm] - Fermat's Primality Test

### ISSUE THREAD

**Issue by MackQian** [iam-abbas/cs-algorithms#92]
# CS - Algorithm
- [ x]  This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information
https://en.wikipedia.org/wiki/Primality_test#Fermat_primality_test
Simple Probabilistic Primality Testing Algorithm using Fermat's Little Theorem
- **Algorithm Name:**
Fermat's Primality Test
- **Language:**
Python

**Comment by MackQian** [comment]
#93

**Comment by MackQian** [comment]
#93

**Comment by VedantParanjape** [comment]
I would love to solve this.
