### ISSUE TITLE
[Algorithm] - Bucket Sort

### ISSUE THREAD

**Issue by ashx404** [iam-abbas/cs-algorithms#94]
# CS - Algorithm
-   This algorithm is not available in the repository currently.
- [ ] If it is, My Algorithm is implemented in a different method.

##  Information

-  Bucket Sort

- C++

**Comment by ashx404** [comment]
can i work on this?

**Comment by reynaldo22** [comment]
want to add bucket sort algorithm?

**Comment by ashx404** [comment]
#95
